version: "3.7"
services:
  selenium-hub:
    image: selenium/hub:3.141.59-zirconium
    container_name: gloria-geans
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:3.141.59-zirconium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
